"""Add order_number and paid_at to orders

Revision ID: ff0d01ab0520
Revises: 2c789e9cc6ec
Create Date: 2026-01-31 23:00:53.418286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0d01ab0520'
down_revision = '2c789e9cc6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_orders_order_number', ['order_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_orders_order_number', type_='unique')
        batch_op.drop_column('paid_at')
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
